DROP TABLE pnprod.LAST_MILE_HD;
CREATE TABLE pnprod.LAST_MILE_HD
(
  ROW_ID                     NUMBER(12)         NOT NULL,
  WE_DATE                    DATE               NOT NULL,                    
  ACCOUNT                    NUMBER(12)         NOT NULL,
  BROWSE_ID                  NUMBER(9)          NOT NULL,
  HOUSEHOLD_ID               NUMBER(9)          NOT NULL,
  ADDRESS_ID                 NUMBER(9)          NOT NULL,
  NAME_SEARCH                VARCHAR2(50),
  ZIP                        VARCHAR2(12),
  QUANTITY                   NUMBER(7),
  PAP_CODE                   VARCHAR2(8),
  PROD_CODE                  VARCHAR2(2),
  RATE_TABLE                 NUMBER(3),
  DLY_COPIES                 NUMBER(7), 
  DLY_COPY_RATE              NUMBER(9,5),
  SUN_COPIES                 NUMBER(7), 
  SUN_COPY_RATE              NUMBER(9,5),
  DLY_SUB_REV                NUMBER(12,5),
  SUN_SUB_REV                NUMBER(12,5), 
  PUB_PAPER                  NUMBER(4),
  CAR_ACCOUNT                NUMBER(12),
  CAR_BROWSE_ID              NUMBER(9),
  CAR_HOUSEHOLD_ID           NUMBER(9),
  CAR_ADDRESS_ID             NUMBER(9),
  CAR_NAME                   VARCHAR2(50),
  CAR_PUB                    NUMBER(4),
  ROUTE_PUB                  NUMBER(4),
  ROUTE                      VARCHAR2(8),
  ROUTE_NAME                 VARCHAR2(30),
  ADI                        NUMBER(4),
  DISTRICT                   VARCHAR2(3),
  DISTRICT_DESC              VARCHAR2(50),
  SUB_DISTRICT               VARCHAR2(4),
  ZONE_CODE                  VARCHAR2(6),
  RATE_CODE                  VARCHAR2(6),
  RATE_METHOD                VARCHAR2(6),
  CAR_RATE_DLY               NUMBER(9,5),
  CAR_RATE_SUN               NUMBER(9,5),
  CAR_AMT_DLY                NUMBER(12,5),
  CAR_AMT_SUN                NUMBER(12,5),
  FIELD_COMP_ADJS            NUMBER(12,5),
  FIELD_CAR_FEE_ADJS         NUMBER(12,5),
  FIELD_CAR_TAKE_FEE         NUMBER(12,5),
  QUAL_INCENTIVE             NUMBER(12,5),
  RETENTION_BONUS            NUMBER(12,5),
  FINDERS_FEE_BONUS          NUMBER(12,5),
  SUB_TIPS_ON_BILL           NUMBER(12,5)
)
  
TABLESPACE CIRC
RESULT_CACHE (MODE DEFAULT)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

CREATE UNIQUE INDEX pnprod.PK_LAST_MILE_HD ON pnprod.LAST_MILE_HD
(ROW_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;

ALTER TABLE pnprod.LAST_MILE_HD ADD (
  CONSTRAINT PK_LAST_MILE_HD 
  PRIMARY KEY
  (ROW_ID)
  USING INDEX pnprod.PK_LAST_MILE_HD
  ENABLE VALIDATE);
  
CREATE INDEX pnprod.IDX_LAST_MILE_WE_ACCT ON pnprod.LAST_MILE_HD
(WE_DATE, ACCOUNT)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_BROWSE_ID ON pnprod.LAST_MILE_HD
(BROWSE_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_HOUSEHOLD_ID ON pnprod.LAST_MILE_HD
(HOUSEHOLD_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_ADDRESS_ID ON pnprod.LAST_MILE_HD
(ADDRESS_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_NAME_WE ON pnprod.LAST_MILE_HD
(NAME_SEARCH,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_ZIP_WE ON pnprod.LAST_MILE_HD
(ZIP,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_WE_CAR_ACCT ON pnprod.LAST_MILE_HD
(WE_DATE,CAR_ACCOUNT)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_CAR_BROWSE_ID ON pnprod.LAST_MILE_HD
(CAR_BROWSE_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_CAR_HOUSEHOLD_ID ON pnprod.LAST_MILE_HD
(CAR_HOUSEHOLD_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;  

CREATE INDEX pnprod.IDX_LAST_MILE_CAR_ADDRESS_ID ON pnprod.LAST_MILE_HD
(CAR_ADDRESS_ID)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL; 

CREATE INDEX pnprod.IDX_LAST_MILE_CAR_NAME_WE ON pnprod.LAST_MILE_HD
(CAR_NAME,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL; 

CREATE INDEX pnprod.IDX_LAST_MILE_ROUTE_WE_PUB ON pnprod.LAST_MILE_HD
(ROUTE,WE_DATE,ROUTE_PUB)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;

CREATE INDEX pnprod.IDX_LAST_MILE_ROUTE_NAME_WE ON pnprod.LAST_MILE_HD
(ROUTE_NAME,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;

CREATE INDEX pnprod.IDX_LAST_MILE_DISTRICT_WE ON pnprod.LAST_MILE_HD
(DISTRICT,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;

CREATE INDEX pnprod.IDX_LAST_MILE_ZONE_WE ON pnprod.LAST_MILE_HD
(ZONE_CODE,WE_DATE)
LOGGING
TABLESPACE CIRC_INDX
NOPARALLEL;

GRANT SELECT ON pnprod.LAST_MILE_HD TO ADDR WITH GRANT OPTION;
GRANT SELECT ON pnprod.LAST_MILE_HD TO ADDR_EXT;
GRANT SELECT ON pnprod.LAST_MILE_HD TO ADDR_READ;
GRANT DELETE, INSERT, SELECT, UPDATE ON pnprod.LAST_MILE_HD TO ADV_RPT WITH GRANT OPTION;
GRANT REFERENCES ON pnprod.LAST_MILE_HD TO ADV_RPT;
GRANT DELETE, INSERT, SELECT, UPDATE ON pnprod.LAST_MILE_HD TO CASH WITH GRANT OPTION;
GRANT SELECT ON pnprod.LAST_MILE_HD TO CIRC_EXT;
GRANT DELETE, INSERT, SELECT, UPDATE ON pnprod.LAST_MILE_HD TO CIRC_FULL;
GRANT SELECT ON pnprod.LAST_MILE_HD TO CIRC_PORT WITH GRANT OPTION;
GRANT DELETE, INSERT, UPDATE ON pnprod.LAST_MILE_HD TO CIRC_PORT;
GRANT SELECT ON pnprod.LAST_MILE_HD TO CIRC_READ;
GRANT DELETE, INSERT, SELECT, UPDATE ON pnprod.LAST_MILE_HD TO CIRC_RPT WITH GRANT OPTION;
GRANT REFERENCES ON pnprod.LAST_MILE_HD TO CIRC_RPT;
GRANT ALTER, DELETE, INDEX, INSERT, REFERENCES, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON pnprod.LAST_MILE_HD TO SALESFORCE;
GRANT SELECT ON pnprod.LAST_MILE_HD TO SEC_PORT WITH GRANT OPTION;
GRANT ALTER, DELETE, INSERT, SELECT, UPDATE, ON COMMIT REFRESH, QUERY REWRITE, DEBUG, FLASHBACK ON pnprod.LAST_MILE_HD TO SF_ROLE;
GRANT SELECT ON pnprod.LAST_MILE_HD TO SOL_WEB WITH GRANT OPTION;