GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO CIRC_EXT;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO CIRC_FULL;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO ADV_RPT WITH GRANT OPTION;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO CIRC_READ;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO CIRC_RPT WITH GRANT OPTION;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO SALESFORCE;
GRANT DEBUG   ON pnprod.LAST_MILE_WKLY_UPDATE TO SALESFORCE;
GRANT EXECUTE ON pnprod.LAST_MILE_WKLY_UPDATE TO SF_ROLE;